function loadInifileAFUA
%loadInifileAFUA loads an ini file with UA and AF module data
global af ua dia
%% make sure DIR is set correctly, otherwise it just writes to the current folder.
%If does not exist, create it. Otherwise read values. If values are not
%present, use default values.

% figure out directory of this function and write/use ini file in same
% directory
a=which('loadInifileAFUA');
[filepath,~,~]=fileparts(a);
fname='afua.ini';
fpath=[filepath,'\',fname];
if ~exist(fpath,'file')
    inifile(fpath,'new');
    
end
% read file. last value is default value.
readKeys = {'af','','active','d',0;...
    'af','params','zrange','d',4;...
    'af','params','zstep','d',1;...
    'af','params','frequency','d',5;...
    'af','params','isAFon','d',0;...
    'af','params','useAcqForAF','d',0;...
    'af','params','channel','d',1;...
    'af','params','isEtlOn','d',0;...
    'af','algorithm','value','d',2;...
    'af','algorithm','operator','','ACMO';...
    'af','','statusGUI','','-';...
    'af','params','displaytoggle','d',0;...
    'af','','afDispHandle','d',NaN;...
    'af','','roisize','d',30;...
    'af','drift','scale','d',13;...
    'af','drift','tuneshift','d',3;...
    'af','drift','on','d',0;...
    'af','drift','mode','s','scanDriftMode';...
    'af','params','thresh','d',0;...
    'af','params','roiDist','d',0;...
    'ua','params','primaryTime','d',30;...
    'ua','params','primaryFreq','d',30;...
    'ua','params','secondaryTime','d',0;...
    'ua','params','secondaryFreq','d',0;...
    'ua','drift','driftON','d',0;...
    'ua','drift','refChannel','d',1;...
    'ua','drift','zoomOutDrift','d',0;...
    'ua','drift','zoomfactor','d',5;...
    'ua','params','zRoof','d',0;...
    'ua','params','preUncageTime','d',5;...
    'ua','params','preUncageFreq','d',60;...
    'ua','params','fovModeOn','d',0;...
    'ua','params','autoAddRefImg','d',1;...
    'ua','params','initialZoom','d',30;...
    'ua','drift','useMaxProjection','d',0;...
    'ua','','UAmodeON','d',0;...
    'af','params','mode','s','multiMode';...
    'dia','init','staggerOn','d',0;...
    'dia','acq','uncagingTimeEst','d',60;...
    'dia','acq','imagingTimeEst','d',60;...
    'dia','acq','preUncageExclusiveTime','d',0;...
    'dia','acq','preUncageExclusivePeriod','d',30;...
    'dia','acq','postUncageExclusiveTime','d',0;...
    'dia','acq','postUncageExclusivePeriod','d',30;...
    'dia','acq','correctRois','d',0;...
    'dia','init','useOnePos','d',0;...
    'dia','acq','pauseOn','d',0;...
    'dia','acq','grabAndTimeOn','d',0;...
    'dia','etlacq','voltToUm','d',59;...
    'dia','etlacq','etlOn','d',0;...
    'dia','etlacq','absZlimit','d',0;...
    'dia','etlacq','autoRange','d',20;...
    'dia','etlacq','voltageMin','d',0;...
    'dia','etlacq','voltageRange','d',0;...
    'dia','etlacq','fovSizeUm','d',240;...
    'dia','etlacq','stackOnlyMode','d','0';...
    'dia','etlacq','umToVoltPoly','d','-1.10207e-09, 4.92359e-07, -1.05204e-04, 1.76956e-02, 3.05858e-02';...
    'dia','etlacq','voltCalcMode','d','2';...
    'dia','etlacq','mirrorTransformPolyX','d','7.670885e-02, -6.369041e-01, 1.021473e+00';...
    'dia','etlacq','mirrorTransformPolyY','d','-5.458245e-02, -1.739482e-01, 1.004293e+00';...
    'dia','acq','initialImagingTime','d',0;...
    'dia','acq','initialImagingPeriod','d',60;...
    'dia','init','doBeamPowerTransform','d',0;...
    'dia','acq','maxPositions','d',5};
data = inifile(fpath,'read',readKeys);
Slist=readKeys(:,1);

Snames={'af','ua','dia'};
for k=1:length(Snames)
    strct_list=ismember(Slist,Snames{k});
    ID1=readKeys(strct_list,2);
    ID2=readKeys(strct_list,3);
    fields1=unique(ID1);
    Sdata=data(strct_list);
    if strcmp(Snames{k},'af')
        for i=1:length(fields1)
            fld1=fields1{i};
            tf=find(ismember(ID1,fld1));
            for j=1:length(ID2(tf))
                if isempty(fld1)
                    af.(ID2{tf(j)})=Sdata{tf(j)};
                else
                    af.(fld1).(ID2{tf(j)})=Sdata{tf(j)};
                end
            end
        end
    elseif strcmp(Snames{k},'ua')
        for i=1:length(fields1)
            fld1=fields1{i};
            tf=find(ismember(ID1,fld1));
            for j=1:length(ID2(tf))
                if isempty(fld1)
                    ua.(ID2{tf(j)})=Sdata{tf(j)};
                else
                    ua.(fld1).(ID2{tf(j)})=Sdata{tf(j)};
                end
            end
        end
    elseif strcmp(Snames{k},'dia')
        for i=1:length(fields1)
            fld1=fields1{i};
            tf=find(ismember(ID1,fld1));
            for j=1:length(ID2(tf))
                if isempty(fld1)
                    dia.(ID2{tf(j)})=Sdata{tf(j)};
                else
                    dia.(fld1).(ID2{tf(j)})=Sdata{tf(j)};
                end
            end
        end
    end
    
end
af.inipath=fpath;
%deal with structures with more than 3 levels
fNames=fieldnames(dia.etlacq);
for i=1:length(fNames)
    dia.etl.acq.(fNames{i})=dia.etlacq.(fNames{i});
end
dia.etlacq=[];
if isfield(dia,'hPos')
    dia.hPos.loadTimeline(fpath);
end
end

