function saveInifileAFUA
%saveInifileAFUA saves an ini file with UA and AF module data
global af ua dia
fpath=af.inipath;
if ~exist(fpath,'file')
    inifile(fpath,'new');
end
% read file autofocus and drift status is not written since it should
% probably start at 'off' for now

writeKeys = {'af','','active',af.active;...
    'af','params','zrange',af.params.zrange;...
    'af','params','zstep',af.params.zstep;...
    'af','params','frequency',af.params.frequency;...
    'af','params','useAcqForAF',af.params.useAcqForAF;...
    'af','params','channel',af.params.channel;...
    'af','params','isAFon',af.params.isAFon;...
    'af','params','isEtlOn',af.params.isEtlOn;...
    'af','algorithm','value',af.algorithm.value;...
    'af','algorithm','operator',af.algorithm.operator;...
    'af','','statusGUI',af.statusGUI;...
    'af','params','displaytoggle',af.params.displaytoggle;...
    'af','','afDispHandle',af.afDispHandle;...
    'af','','roisize',af.roisize;...
    'af','drift','on',af.drift.on;...
    'af','drift','scale',af.drift.scale;...
    'af','drift','tuneshift',af.drift.tuneshift;...
    'af','drift','mode',af.drift.mode;...
    'af','params','thresh',af.params.thresh;...
    'af','params','roiDist',af.params.roiDist;...
    'ua','params','primaryTime',ua.params.primaryTime;...
    'ua','params','primaryFreq',ua.params.primaryFreq;...
    'ua','params','secondaryTime',ua.params.secondaryTime;...
    'ua','params','secondaryFreq',ua.params.secondaryFreq;...
    'ua','params','zRoof',ua.params.zRoof;...
    'ua','drift','refChannel',ua.drift.refChannel;...
    'ua','drift','zoomOutDrift',ua.drift.zoomOutDrift;...
    'ua','drift','driftON',ua.drift.driftON;...    
    'ua','drift','zoomfactor',ua.drift.zoomfactor;...
    'ua','params','preUncageTime',ua.params.preUncageTime;...
    'ua','params','preUncageFreq',ua.params.preUncageFreq;...
    'ua','params','autoAddRefImg',ua.params.autoAddRefImg;...
    'ua','params','initialZoom',ua.params.initialZoom;...
    'ua','drift','useMaxProjection',ua.drift.useMaxProjection;...
    'af','params','mode',af.params.mode;...
    'dia','init','staggerOn',dia.init.staggerOn;...
    'dia','acq','uncagingTimeEst',dia.acq.uncagingTimeEst;...
    'dia','acq','imagingTimeEst',dia.acq.imagingTimeEst;...
    'dia','acq','preUncageExclusiveTime',dia.acq.preUncageExclusiveTime;...
    'dia','acq','preUncageExclusivePeriod',dia.acq.preUncageExclusivePeriod;...
    'dia','acq','postUncageExclusiveTime',dia.acq.postUncageExclusiveTime;...
    'dia','acq','postUncageExclusivePeriod',dia.acq.postUncageExclusivePeriod;...
    'dia','acq','correctRois',dia.acq.correctRois;...
    'dia','etlacq','voltToUm',dia.etl.acq.voltToUm;...
    'dia','etlacq','etlOn',dia.etl.acq.etlOn;...
    'dia','etlacq','absZlimit',dia.etl.acq.absZlimit;...
    'dia','etlacq','autoRange',dia.etl.acq.autoRange;...
    'dia','etlacq','fovSizeUm',dia.etl.acq.fovSizeUm;...
    'dia','etlacq','stackOnlyMode',dia.etl.acq.stackOnlyMode;...
    'dia','etlacq','umToVoltPoly',dia.etl.acq.umToVoltPoly;...
    'dia','etlacq','voltCalcMode',dia.etl.acq.voltCalcMode;...
    'dia','etlacq','mirrorTransformPolyX',dia.etl.acq.mirrorTransformPolyX;...
    'dia','etlacq','mirrorTransformPolyY',dia.etl.acq.mirrorTransformPolyY;...
    'dia','acq','initialImagingTime',dia.acq.initialImagingTime;...
    'dia','acq','initialImagingPeriod',dia.acq.initialImagingPeriod;...
    'dia','init','doBeamPowerTransform',dia.init.doBeamPowerTransform;...
    'dia','acq','maxPositions',dia.acq.maxPositions};
inifile(fpath,'write',writeKeys,'plain');

[timePath,~,~]=fileparts(af.inipath);
timepath=[timePath,'\timings.mat'];
timelineSetup=dia.hPos.timelineSetup;
staggerTime=dia.hPos.staggerTime;
collectFOVstackWhenDone = dia.hPos.collectFOVstackWhenDone;

save(timepath,'timelineSetup','staggerTime','collectFOVstackWhenDone');

end

