%Physiology scope software
%Emiliano Rial Verde
%October-November 2005
%December 2005 Version 2
%Updated for better performance in Matlab 2006a. November 2006
%acq_winmanager.exe added November 2006
%Defaults loader added in January 2007
%Seal test through analog output added March 2007
%
%
%ERV Physiology Scope. Version 2.0
%
%Scope to "look" at up to 2 MultiClamp Amplifiers with 2 channels each, or
%the PC soundcard. With Multiclamp Amplifiers, National Instruments data
%acquisition boards should be used.
%
%Initiate the MultiClamp Commander before starting this application because the
%MultiClamp Messenger (MCTeleClient.exe) needs to find a Commander open to
%establish a connection with the amplifier.
%
%The Scope can use the Sync outputs of the amplifiers to synchronize the seal
%test pulses and calculate series, input resistance, and membrane
%capaciatnce. Note that if you choose to do that, the seal test checkbox in the
%active channel of the MultiClamp Commander needs to be checked.
%
%The other possibility is to use one of the analog outputs of the card to
%send the test pulse to the command BNC of the amplifier. I prefer this
%option.
%
%For the Scope to communicate with the Multiclamp amplifiers, make sure to
%copy all the necessary files to C:\Program Files\acq\,
%otherwise the MultiClamp Telegraph Client will not work properly, and the
%Scope will not read the data (and probably crash).
%Files to copy in C:\Program Files\acq\:
%MCTeleClient_readme.txt 
%MCTeleClient.exe
%
%Files to copy in C:\Program Files\acq\amps\:
%amp_serials.erv 
%Note: This is a text file that can be opened with Notepad.
%      Update this file with the correct Serial numbers of the installed amplifiers
%      every time the program is set up in a new machine.
%
%Files to copy in C:\Program Files\acq\settings\:
%basic.erv
%Note: This is a text file, editable with Notepad, containing the default
%settings of the Scope and Recorder windows. As many files as desired can
%be created and placed in the C:\Program Files\acq\settings\ folder. The
%Scope window will recognize these files and show them under the "Defaults"
%popup. Selecting one of these files, all the included parameters will be
%automatically loaded. This feature is useful to create and store settings
%for different protocols or experiments.
%
%Files to copy in C:\Program Files\acq\stims\:
%Any stimulation file to be output through the analog outputs
%These should be .mat files containing a vector called outputdata with the values in volts of each sample to be output
%
%All matlab script files belonging to this application and acq_winmanager.exe should be copied in
%the MATLAB root folder, work subfolder, inside a folder called Physiology.
%
%
%Note that acq_winmanager.exe is an executable file created with AutoIt
%to manage windows outside this Physiology software. I use it to minimize
%Matlab and to minimize or close the MultiClamp Messenger. The .exe file needs to
%be called with 2 parameters: 1) The window name, and 2) the action (minimize, close).
%Some AntiVirus Software recognizes this .exe file as a Trojan and deletes
%it. Make sure to disable the AntiVirus for the work\Physiology\ folder.
%
%
%Emiliano M. Rial Verde
%2005
%emiliano@rialverde.com



%Minimizes Matlab window
eval(['! "' ,matlabroot, '\work\Physiology\acq_winmanager.exe" "MATLAB" "minimize"']);

%Starts MultiClamp Messenger V2 and minimizes the window
winopen('C:\Program Files\acq\MCTeleClient.exe');
eval(['! "' ,matlabroot, '\work\Physiology\acq_winmanager.exe" "MultiClamp Messenger" "minimize"']);

if exist('cmtimer', 'var')
    delete(cmtimer)
end
if exist('ai1', 'var')
    delete(ai1)
end
if exist('ai2', 'var')
    delete(ai2)
end
close all
clear all


warning('off', 'all');

%Scope window
%Closing this window causes all other Matlab figure windows to be closed, all variables in the workspace cleared,
%and the MultiClamp Messenger to be closed.
h0 = figure(...
'Units','normalized',...
'MenuBar','none',...
'Name','ERV Physiology Scope. V 2.0',...
'NumberTitle','off',...
'Position',[0.08 0.3 0.4 0.64],...
'doublebuffer', 'on', ...
'DeleteFcn', ['close all;', ...
   'clear all;', ...
   'eval([''! "'' ,matlabroot, ''\work\Physiology\acq_winmanager.exe" "MultiClamp Messenger" "close"'']);'], ...
'Tag','mainwindow');
a=get(gcf, 'Color');

%Defaults loader
h1=uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.64 0.95 0.08 0.03],...
'Style', 'text', ...
'String','Defaults:',...
'FontSize', 12);
set(h1, 'BackgroundColor', a);
d=dir('C:\Program Files\acq\settings\*.erv');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.725 0.95 0.265 0.03],...
'Style', 'popup', ...
'String',{d.name},...
'Callback', 'acq_defaults; acqmode=1; startacq;', ...
'ToolTipString', 'Loads the selected defaults from .erv file', ...
'FontSize', 10, ...
'Tag','defaultspopup');

%Resets National Instruments card
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Callback', 'acqmode=1; startacq;', ...
'Position',[0.64 0.925 0.14 0.02],...
'String','Reset NI card',...
'Callback', 'resetNIcard', ...
'Tag','resetNIcardbutton');

%Resets graphic axes
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Callback', 'acqmode=1; startacq;', ...
'Position',[0.79 0.925 0.2 0.02],...
'String','Reset graphics',...
'Tag','resetgraphbutton');

%Acquisition device and channel controls
h1 = uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.01 0.95 0.08 0.03],...
'Style', 'text', ...
'String','Device:',...
'HorizontalAlignment', 'left', ...
'FontSize', 12);
set(h1, 'BackgroundColor', a);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.09 0.95 0.13 0.03],...
'Style', 'popup', ...
'String','nidaq|winsound',...
'Value', 1, ...
'Callback', ['if get(findobj(''Tag'', ''devicepopup''), ''Value'')==2;', ...
    'set(findobj(''Tag'', ''triggeredit''), ''String'', ''nan'');', ...
    'set(findobj(''Tag'', ''a1ch1edit''), ''String'', ''1'');', ...
    'set(findobj(''Tag'', ''a1ch2edit''), ''String'', ''2'');', ...
    'elseif get(findobj(''Tag'', ''devicepopup''), ''Value'')==1;', ...
    'set(findobj(''Tag'', ''triggeredit''), ''String'', ''5'');', ...
    'set(findobj(''Tag'', ''a1ch1edit''), ''String'', ''12'');', ...
    'set(findobj(''Tag'', ''a1ch2edit''), ''String'', ''nan'');', ...
    'end;', ...
    'acqmode=1; startacq;'], ...
'ToolTipString', 'Acquisition device', ...
'FontSize', 10, ...
'Tag','devicepopup');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Style', 'radio', ...
'Position',[0.01 0.92 0.1 0.02],...
'String','Dflt. board',...
'Callback', ['if get(findobj(''Tag'', ''defaultboardradio''), ''Value'')==1; ', ...
    'set(findobj(''Tag'', ''selectboardradio''), ''Value'', 0);', ...
    'else; set(findobj(''Tag'', ''selectboardradio''), ''Value'', 1); end; acqmode=1; startacq;'], ...
'Value', 1, ...
'ToolTipString', 'Default device number is 1 for both, AI and AO', ...
'FontSize', 8, ...
'Tag', 'defaultboardradio');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.12 0.92 0.1 0.02],...
'Style', 'radio', ...
'String','Sel. board',...
'Callback', ['if get(findobj(''Tag'', ''selectboardradio''), ''Value'')==1; ', ...
    'set(findobj(''Tag'', ''defaultboardradio''), ''Value'', 0);', ...
    'else; set(findobj(''Tag'', ''defaultboardradio''), ''Value'', 1); end; acqmode=1; startacq;'], ...
'ToolTipString', 'Change device number selection for AI and AO', ...
'FontSize', 8, ...
'Tag', 'selectboardradio');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.01 0.89 0.22 0.03],...
'Style', 'text', ...
'String','Channels to acquire',...
'BackgroundColor', a, ...
'FontSize', 12);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.01 0.855 0.16 0.03],...
'Style', 'text', ...
'String','Trigger channel:',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 10);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.17 0.855 0.05 0.035],...
'Style', 'edit', ...
'String', 'nan',...
'ToolTipString', 'Channel or channels to use for trigger. Enter "nan" for continuous mode (no trigger). Separate with commas if more than one (different triggers for amplifier 1 and 2 for example).', ...
'FontSize', 8, ...
'Tag','triggeredit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.01 0.82 0.16 0.03],...
'Style', 'text', ...
'String','A 1 Hs 1 channel:',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 10);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.17 0.82 0.05 0.035],...
'Style', 'edit', ...
'String', 'nan',...
'ToolTipString', 'Channel to use for headstage 1 of amplifier 1. Enter "nan" not to acquire.', ...
'FontSize', 8, ...
'Tag','a1ch1edit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.01 0.785 0.16 0.03],...
'Style', 'text', ...
'String','A 1 Hs 2 channel:',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 10);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.17 0.785 0.05 0.035],...
'Style', 'edit', ...
'String', 'nan',...
'ToolTipString', 'Channel to use for headstage 2 of amplifier 1. Enter "nan" not to acquire.', ...
'FontSize', 8, ...
'Tag','a1ch2edit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.01 0.75 0.16 0.03],...
'Style', 'text', ...
'String','A 2 Hs 1 channel:',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 10);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.17 0.75 0.05 0.035],...
'Style', 'edit', ...
'String', 'nan',...
'ToolTipString', 'Channel to use for headstage 1 of amplifier 2. Enter "nan" not to acquire.', ...
'FontSize', 8, ...
'Tag','a2ch1edit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.01 0.715 0.16 0.03],...
'Style', 'text', ...
'String','A 2 Hs 2 channel:',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 10);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.17 0.715 0.05 0.035],...
'Style', 'edit', ...
'String', 'nan',...
'ToolTipString', 'Channel to use for headstage 2 of amplifier 2. Enter "nan" not to acquire.', ...
'FontSize', 8, ...
'Tag','a2ch2edit');


%Test pulse controls
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.23 0.955 0.17 0.03],...
'Style', 'text', ...
'String','Test pulse ampl. (mV):',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 8);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.4 0.955 0.05 0.035],...
'Style', 'edit', ...
'String','-5',...
'FontSize', 12, ...
'Tag','testamplitudeedit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.23 0.92 0.17 0.03],...
'Style', 'text', ...
'String','Test pulse durat. (ms):',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 8);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.4 0.92 0.05 0.035],...
'Style', 'edit', ...
'String','25',...
'FontSize', 12, ...
'Tag','testlengthedit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.455 0.955 0.12 0.03],...
'Style', 'text', ...
'String','Rs window (ms):',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 8);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.58 0.955 0.05 0.035],...
'Style', 'edit', ...
'String','5',...
'FontSize', 12, ...
'ToolTipString', 'Length of the window over which peak current is searched to calculate series resistance.', ... 
'Tag','rsedit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.455 0.92 0.12 0.03],...
'Style', 'text', ...
'String','Ri window (ms):',...
'HorizontalAlignment', 'left', ...
'BackgroundColor', a, ...
'FontSize', 8);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.58 0.92 0.05 0.035],...
'Style', 'edit', ...
'String','5',...
'FontSize', 12, ...
'ToolTipString', 'Length of the window over which current is averaged to calculate input resistance.', ... 
'Tag','riedit');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.455 0.885 0.175 0.03],...
'Style', 'radio', ...
'String','Capacitance calc.',...
'FontSize', 8, ...
'BackgroundColor', a, ...
'TooltipString', 'Perform membrane capacitance calculation', ...
'Tag', 'cmradio');

%Analog output
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.575 0.84 0.06 0.07],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.58 0.88 0.05 0.025],...
'String','AO',...
'Style', 'text', ...
'BackgroundColor', a, ...
'FontWeight', 'bold', ...
'FontSize', 8);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.58 0.845 0.05 0.03],...
'String','nan',...
'Callback', 'acqmode=1; startacq;', ...
'Style', 'edit', ...
'FontSize', 8, ...
'ToolTipString', 'Analog output channel to send the seal test', ...
'Tag', 'aosealedit');


%V/I clamp controls
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.225 0.91 0.13 0.002],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.225 0.713 0.13 0.002],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.225 0.713 0.002 0.199],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.355 0.713 0.002 0.199],...
'Style', 'frame', ...
'BackgroundColor', 'k');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.23 0.88 0.12 0.03],...
'Style', 'text', ...
'String','Modes',...
'FontSize', 12, ...
'BackgroundColor', a, ...
'FontWeight', 'Bold');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.23 0.82 0.12 0.03],...
'Style', 'Text', ...
'String','?',...
'FontSize', 8, ...
'Tag', 'modeamp1ch1text');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.23 0.785 0.12 0.03],...
'Style', 'Text', ...
'String','?',...
'FontSize', 8, ...
'Tag', 'modeamp1ch2text');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.23 0.75 0.12 0.03],...
'Style', 'Text', ...
'String','?',...
'FontSize', 8, ...
'Tag', 'modeamp2ch1text');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.23 0.715 0.12 0.03],...
'Style', 'Text', ...
'String','?',...
'FontSize', 8, ...
'Tag', 'modeamp2ch2text');


%Gain controls
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.36 0.91 0.09 0.002],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.36 0.713 0.19 0.002],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.358 0.713 0.002 0.199],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.55 0.713 0.002 0.17],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.45 0.88 0.102 0.002],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.45 0.88 0.002 0.032],...
'Style', 'frame', ...
'BackgroundColor', 'k');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.36 0.88 0.09 0.03],...
'String','Gains',...
'Style', 'text', ...
'FontSize', 12, ...
'BackgroundColor', a, ...
'FontWeight', 'bold');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.36 0.832 0.19 0.03],...
'String','Hs 1 | Amp. #1 | Hs 2',...
'Style', 'text', ...
'BackgroundColor', a, ...
'FontSize', 10);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.36 0.8 0.09 0.03],...
'String','?',...
'Style', 'text', ...
'FontSize', 10, ...
'ToolTipString', 'Gain of amplifier 1, headstage 1. 1 is 0.5V/nA or 10mV/mV.', ...
'Tag', 'amp1ch1gaintext');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.46 0.8 0.09 0.03],...
'String','?',...
'Style', 'text', ...
'FontSize', 10, ...
'ToolTipString', 'Gain of amplifier 1, headstage 2. 1 is 0.5V/nA or 10mV/mV.', ...
'Tag', 'amp1ch2gaintext');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.36 0.748 0.19 0.03],...
'String','Hs 1 | Amp. #2 | Hs 2',...
'Style', 'text', ...
'BackgroundColor', a, ...
'FontSize', 10);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.36 0.715 0.09 0.03],...
'String','?',...
'Style', 'text', ...
'FontSize', 10, ...
'ToolTipString', 'Gain of amplifier 2, headstage 1. 1 is 0.5V/nA or 10mV/mV.', ...
'Tag', 'amp2ch1gaintext');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.46 0.715 0.09 0.03],...
'String','?',...
'Style', 'text', ...
'FontSize', 10, ...
'ToolTipString', 'Gain of amplifier 2, headstage 2. 1 is 0.5V/nA or 1mV/mV.', ...
'Tag', 'amp2ch2gaintext');


%Acquisition rate
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.64 0.84 0.14 0.07],...
'Style', 'frame', ...
'BackgroundColor', 'k');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.645 0.88 0.13 0.025],...
'String','Acquisition rate',...
'Style', 'text', ...
'BackgroundColor', a, ...
'FontWeight', 'bold', ...
'FontSize', 8);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.645 0.845 0.13 0.03],...
'String','10000',...
'Callback', 'acqmode=1; startacq;', ...
'Style', 'edit', ...
'FontSize', 8, ...
'ToolTipString', 'Acquisition rate in Hz', ...
'Tag', 'samplerateedit');


%Start acquisition buttons and status legend
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Callback', 'acqmode=2; startacq;', ...
'Position',[0.79 0.86 0.2 0.06],...
'String','Start Seal',...
'FontSize', 14, ...
'FontWeight', 'bold', ...
'Tag','startsealbutton');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.79 0.79 0.2 0.05],...
'Style', 'text', ...
'String','Ready',...
'FontSize', 14, ...
'FontWeight', 'bold', ...
'BackgroundColor', 'y', ...
'ForegroundColor', 'r', ...
'Tag','statustext');


%Rs Ri Cm indicators
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.665 0.13 0.035],...
'Style', 'text', ...
'String','Rs Ri Cm',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'BackgroundColor', 'w', ...
'ForegroundColor', 'k', ...
'Tag', 'rsricm1', ...
'Visible', 'off');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.62 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'BackgroundColor', 'k', ...
'TooltipString', 'Series resistance in megaohms (1st channel)', ...
'ForegroundColor', 'w', ...
'Tag', 'rs1text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.58 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Input resistance in megaohms (1st channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'ri1text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.54 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Membrane capaciatance in picofaradays (1st channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'cm1text', ...
'Visible', 'off');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.48 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'BackgroundColor', 'k', ...
'TooltipString', 'Series resistance in megaohms (3rd channel)', ...
'ForegroundColor', 'w', ...
'Tag', 'rs3text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.44 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Input resistance in megaohms (3rd channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'ri3text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.4 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Membrane capaciatance in picofaradays (3rd channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'cm3text', ...
'Visible', 'off');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.345 0.13 0.035],...
'Style', 'text', ...
'String','Rs Ri Cm',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'BackgroundColor', 'w', ...
'ForegroundColor', 'k', ...
'Tag', 'rsricm2', ...
'Visible', 'off');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.3 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'BackgroundColor', 'k', ...
'TooltipString', 'Series resistance in megaohms (2nd channel)', ...
'ForegroundColor', 'w', ...
'Tag', 'rs2text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.26 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Input resistance in megaohms (2nd channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'ri2text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.22 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Membrane capaciatance in picofaradays (2nd channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'cm2text', ...
'Visible', 'off');

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.16 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'BackgroundColor', 'k', ...
'TooltipString', 'Series resistance in megaohms (4th channel)', ...
'ForegroundColor', 'w', ...
'Tag', 'rs4text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.12 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Input resistance in megaohms (4th channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'ri4text', ...
'Visible', 'off');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.86 0.08 0.13 0.04],...
'Style', 'text', ...
'String','-',...
'FontSize', 12, ...
'FontWeight', 'bold', ...
'TooltipString', 'Membrane capaciatance in picofaradays (4th channel)', ...
'BackgroundColor', 'k', ...
'ForegroundColor', 'w', ...
'Tag', 'cm4text', ...
'Visible', 'off');


%Amplifier serial numbers
txt=fopen('C:\Program Files\acq\amps\amp_serials.erv', 'r');
b=textscan(txt, '%s');
b=b{:};
fclose(txt);

uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.56 0.8 0.12 0.03],...
'Style', 'text', ...
'String','Amplifier 1: ',...
'FontSize', 12);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.68 0.8 0.105 0.03],...
'Style', 'edit', ...
'String',b{1},...
'Callback', 'acqmode=1; startacq;', ...
'FontSize', 12, ...
'Tag', 'amp1serialtext');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.56 0.715 0.12 0.03],...
'Style', 'text', ...
'String','Amplifier 2: ',...
'FontSize', 12);
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.68 0.715 0.105 0.03],...
'Style', 'edit', ...
'String',b{2},...
'Callback', 'acqmode=1; startacq;', ...
'FontSize', 12, ...
'Tag', 'amp2serialtext');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.56 0.7575 0.12 0.03],...
'Callback', 'acq_amp_serials;', ...
'String','Select Amps',...
'FontSize', 12);


%Y axes auto scale and zoom
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.87 0.715 0.13 0.035],...
'Style', 'radio', ...
'String','Auto scale',...
'FontSize', 12, ...
'BackgroundColor', a, ...
'TooltipString', 'Auto scale the Y axes', ...
'Callback', ['if get(findobj(''Tag'', ''autoscaleradio''), ''Value'')==1;', ...
    'set(findobj(''Tag'', ''zoomtext''), ''Visible'', ''off'');', ...
    'set(findobj(''Tag'', ''zoomplusbutton''), ''Visible'', ''off'');', ...
    'set(findobj(''Tag'', ''zoomminusbutton''), ''Visible'', ''off'');', ...
    'set(findobj(''Tag'', ''zoomresetbutton''), ''Visible'', ''off'');', ...
    'set(findobj(''Tag'', ''autocenterradio''), ''Value'', 0);', ...
    'set(findobj(''Tag'', ''autocenterradio''), ''Visible'', ''off'');', ...
    'set(findobj(''Tag'', ''autocentertext''), ''Visible'', ''off'');', ...
    'yaxesscalefactor=1;', ...
    'elseif get(findobj(''Tag'', ''autoscaleradio''), ''Value'')==0;', ...
    'set(findobj(''Tag'', ''zoomtext''), ''Visible'', ''on'');', ...
    'set(findobj(''Tag'', ''zoomplusbutton''), ''Visible'', ''on'');', ...
    'set(findobj(''Tag'', ''zoomminusbutton''), ''Visible'', ''on'');', ...
    'set(findobj(''Tag'', ''zoomresetbutton''), ''Visible'', ''on'');', ...
    'set(findobj(''Tag'', ''autocenterradio''), ''Visible'', ''on'');', ...
    'set(findobj(''Tag'', ''autocentertext''), ''Visible'', ''on'');', ...
    'yaxesscalefactor=1;', ...
    'end;'], ...
'Tag', 'autoscaleradio');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.79 0.75 0.05 0.035],...
'Style', 'radio', ...
'String','Auto',...
'Callback', ['if get(findobj(''Tag'', ''autocenterradio''), ''Value'')==1;', ...
    'set(findobj(''Tag'', ''autoscaleradio''), ''Value'', 0);', ...
    'end;'], ...
'HorizontalAlignment', 'right', ...
'FontSize', 12, ...
'BackgroundColor', a, ...
'TooltipString', 'Auto center the trace in the Y axis', ...
'Tag', 'autocenterradio');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.79 0.715 0.05 0.035],...
'Style', 'text', ...
'HorizontalAlignment', 'right', ...
'String','center',...
'FontSize', 12, ...
'BackgroundColor', a, ...
'TooltipString', 'Auto center the trace in the Y axis', ...
'Tag', 'autocentertext');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.874 0.745 0.05 0.035],...
'Style', 'text', ...
'String','Zoom',...
'FontSize', 10, ...
'BackgroundColor', a, ...
'Tag', 'zoomtext');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.845 0.75 0.033 0.035],...
'String','Reset',...
'Callback', 'yaxesscalefactor=1;', ...
'TooltipString', 'Y axes Zoom Reset', ...
'Tag', 'zoomresetbutton');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.922 0.75 0.031 0.035],...
'String','+',...
'Callback', 'yaxesscalefactor=yaxesscalefactor*0.5;', ...
'FontSize', 14, ...
'TooltipString', 'Y axes Zoom In', ...
'Tag', 'zoomplusbutton');
uicontrol(...
'Parent',h0,...
'Units','normalized',...
'Position',[0.955 0.75 0.031 0.035],...
'String','-',...
'Callback', 'yaxesscalefactor=yaxesscalefactor*1.5;', ...
'FontSize', 14, ...
'TooltipString', 'Y axes Zoom Out', ...
'Tag', 'zoomminusbutton');

acq_recwin; %Opens the recorder window.
acq_defaults; %Loads the default values for the scope and recorder windows from erv file.
acq2; %Selects the acquisition board, prepares the axes for acquisition, and gets the test pulse information.