%Physiology scope software
%Emiliano Rial Verde
%October-November 2005
%Updated for better performance in Matlab 2006a. November 2006
%
%Scope graphs layout script

%Deletes axes before re-commencing
for i=1:length(scopeaxes)
    eval(['set(scopeaxes{', num2str(i), '}, ''Visible'', ''off'');', ...
        'delete(scopeaxes{', num2str(i), '});']);
end
clear scopeaxes p pcm;

%Resets the trace number for online trace averaging
onlinetraceaveragen=0;

%Resets the Y axes scale factor
yaxesscalefactor=1;

%Axes
if ampchannelnum==1
    figure(findobj('tag', 'mainwindow'));
    axes('XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'Position', [0.1 0.1 0.75 0.6]);
    xlabel('Time in ms')
    ylabels{1}=ylabel(defaultyaxis(1,:));
    [scopeaxes{1}, p{1}, pcm{1}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{1}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{1}=[];
    set(scopeaxes{1}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{1}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{1}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{1}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    set(findobj('Tag', 'rsricm1'), 'Visible', 'on');
    set(findobj('Tag', 'rs1text'), 'Visible', 'on');
    set(findobj('Tag', 'ri1text'), 'Visible', 'on');
    set(findobj('Tag', 'cm1text'), 'Visible', 'on');
    set(findobj('Tag', 'rsricm2'), 'Visible', 'off');
    set(findobj('Tag', 'rs2text'), 'Visible', 'off');
    set(findobj('Tag', 'ri2text'), 'Visible', 'off');
    set(findobj('Tag', 'cm2text'), 'Visible', 'off');
    set(findobj('Tag', 'rs3text'), 'Visible', 'off');
    set(findobj('Tag', 'ri3text'), 'Visible', 'off');
    set(findobj('Tag', 'cm3text'), 'Visible', 'off');
    set(findobj('Tag', 'rs4text'), 'Visible', 'off');
    set(findobj('Tag', 'ri4text'), 'Visible', 'off');
    set(findobj('Tag', 'cm4text'), 'Visible', 'off');
    
elseif ampchannelnum==2
    figure(findobj('tag', 'mainwindow'));
    axes('XLim', defaulttimescalerange, ...
        'XTickLabel', {}, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'Position', [0.1 0.4 0.75 0.3]);
    ylabels{1}=ylabel(defaultyaxis(1,:));
    [scopeaxes{1}, p{1}, pcm{1}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{1}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{1}=[];
    set(scopeaxes{1}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{1}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{1}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{1}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');

    axes('XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'Position', [0.1 0.08 0.75 0.3]);
    xlabel('Time in ms')
    ylabels{2}=ylabel(defaultyaxis(2,:));
    [scopeaxes{2}, p{2}, pcm{2}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{2}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{2}=[];
    set(scopeaxes{2}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{2}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{2}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{2}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    set(findobj('Tag', 'rsricm1'), 'Visible', 'on');
    set(findobj('Tag', 'rs1text'), 'Visible', 'on');
    set(findobj('Tag', 'ri1text'), 'Visible', 'on');
    set(findobj('Tag', 'cm1text'), 'Visible', 'on');
    set(findobj('Tag', 'rsricm2'), 'Visible', 'on');
    set(findobj('Tag', 'rs2text'), 'Visible', 'on');
    set(findobj('Tag', 'ri2text'), 'Visible', 'on');
    set(findobj('Tag', 'cm2text'), 'Visible', 'on');
    set(findobj('Tag', 'rs3text'), 'Visible', 'off');
    set(findobj('Tag', 'ri3text'), 'Visible', 'off');
    set(findobj('Tag', 'cm3text'), 'Visible', 'off');
    set(findobj('Tag', 'rs4text'), 'Visible', 'off');
    set(findobj('Tag', 'ri4text'), 'Visible', 'off');
    set(findobj('Tag', 'cm4text'), 'Visible', 'off');
    
elseif ampchannelnum==3
    figure(findobj('tag', 'mainwindow'));
    axes('XLim', defaulttimescalerange, ...
        'XTickLabel', {}, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'FontSize', 8, ...
        'Position', [0.1 0.4 0.34 0.3]);
    ylabels{1}=ylabel(defaultyaxis(1,:), 'FontSize', 8, 'VerticalAlignment', 'middle');
    [scopeaxes{1}, p{1}, pcm{1}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{1}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{1}=[];
    set(scopeaxes{1}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{1}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{1}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{1}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    
    axes('XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'FontSize', 8, ...
        'Position', [0.1 0.08 0.34 0.3]);
    xlabel('Time in ms', 'FontSize', 8)
    ylabels{2}=ylabel(defaultyaxis(2,:), 'FontSize', 8, 'VerticalAlignment', 'middle');
    [scopeaxes{2}, p{2}, pcm{2}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{2}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{2}=[];
    set(scopeaxes{2}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{2}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{2}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{2}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    
    axes('XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'FontSize', 8, ...
        'Position', [0.51 0.4 0.34 0.3]);
    xlabel('Time in ms')
    ylabels{3}=ylabel(defaultyaxis(3,:), 'FontSize', 8, 'VerticalAlignment', 'middle');
    [scopeaxes{3}, p{3}, pcm{3}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{3}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{3}=[];
    set(scopeaxes{3}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{3}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{3}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{3}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    set(findobj('Tag', 'rsricm1'), 'Visible', 'on');
    set(findobj('Tag', 'rs1text'), 'Visible', 'on');
    set(findobj('Tag', 'ri1text'), 'Visible', 'on');
    set(findobj('Tag', 'cm1text'), 'Visible', 'on');
    set(findobj('Tag', 'rsricm2'), 'Visible', 'on');
    set(findobj('Tag', 'rs2text'), 'Visible', 'on');
    set(findobj('Tag', 'ri2text'), 'Visible', 'on');
    set(findobj('Tag', 'cm2text'), 'Visible', 'on');
    set(findobj('Tag', 'rs3text'), 'Visible', 'on');
    set(findobj('Tag', 'ri3text'), 'Visible', 'on');
    set(findobj('Tag', 'cm3text'), 'Visible', 'on');
    set(findobj('Tag', 'rs4text'), 'Visible', 'off');
    set(findobj('Tag', 'ri4text'), 'Visible', 'off');
    set(findobj('Tag', 'cm4text'), 'Visible', 'off');
    
elseif ampchannelnum==4
    figure(findobj('tag', 'mainwindow'));
    axes('XLim', defaulttimescalerange, ...
        'XTickLabel', {}, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'FontSize', 8, ...
        'Position', [0.1 0.4 0.34 0.3]);
    ylabels{1}=ylabel(defaultyaxis(1,:), 'FontSize', 8, 'VerticalAlignment', 'middle');
    [scopeaxes{1}, p{1}, pcm{1}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{1}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{1}=[];
    set(scopeaxes{1}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{1}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{1}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{1}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    
    axes('XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'FontSize', 8, ...
        'Position', [0.1 0.08 0.34 0.3]);
    xlabel('Time in ms', 'FontSize', 8)
    ylabels{2}=ylabel(defaultyaxis(2,:), 'FontSize', 8, 'VerticalAlignment', 'middle');
    [scopeaxes{2}, p{2}, pcm{2}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{2}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{2}=[];
    set(scopeaxes{2}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{2}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{2}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{2}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    
    axes('XLim', defaulttimescalerange, ...
        'XTickLabel', {}, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'FontSize', 8, ...
        'Position', [0.51 0.4 0.34 0.3]);
    ylabels{3}=ylabel(defaultyaxis(3,:), 'FontSize', 8, 'VerticalAlignment', 'middle');
    [scopeaxes{3}, p{3}, pcm{3}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{3}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{3}=[];
    set(scopeaxes{3}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{3}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{3}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{3}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    
    axes('XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Units', 'normalized', ...
        'FontSize', 8, ...
        'Position', [0.51 0.08 0.34 0.3]);
    xlabel('Time in ms', 'FontSize', 8)
    ylabels{4}=ylabel(defaultyaxis(4,:), 'FontSize', 8, 'VerticalAlignment', 'middle');
    [scopeaxes{4}, p{4}, pcm{4}]=plotyy(timescale, zeros(samplespertrigger,1), timescale, zeros(samplespertrigger,1));
    hold on
    pav{4}=plot(timescale, zeros(samplespertrigger,1), 'c', 'visible', 'off');
    hold off
    onlinetraceaverage{4}=[];
    set(scopeaxes{4}(1), 'XLim', defaulttimescalerange, ...
        'YTickMode', 'auto', ...
        'YTickLabelMode', 'auto', ...
        'YMinorTick', 'on', ...
        'NextPlot', 'replacechildren', ...
        'YColor', 'k');
    set(scopeaxes{4}(2), 'XLim', defaulttimescalerange, ...
        'NextPlot', 'replacechildren', ...
        'Visible', 'off');
    set(p{4}, 'LineStyle', '-', 'Color', 'b');
    set(pcm{4}, 'Linestyle', '-', 'Color', 'r', 'LineWidth', 2, 'Visible', 'off');
    set(findobj('Tag', 'rsricm1'), 'Visible', 'on');
    set(findobj('Tag', 'rs1text'), 'Visible', 'on');
    set(findobj('Tag', 'ri1text'), 'Visible', 'on');
    set(findobj('Tag', 'cm1text'), 'Visible', 'on');
    set(findobj('Tag', 'rsricm2'), 'Visible', 'on');
    set(findobj('Tag', 'rs2text'), 'Visible', 'on');
    set(findobj('Tag', 'ri2text'), 'Visible', 'on');
    set(findobj('Tag', 'cm2text'), 'Visible', 'on');
    set(findobj('Tag', 'rs3text'), 'Visible', 'on');
    set(findobj('Tag', 'ri3text'), 'Visible', 'on');
    set(findobj('Tag', 'cm3text'), 'Visible', 'on');
    set(findobj('Tag', 'rs4text'), 'Visible', 'on');
    set(findobj('Tag', 'ri4text'), 'Visible', 'on');
    set(findobj('Tag', 'cm4text'), 'Visible', 'on');
end